name: Build check

on:
    workflow_dispatch:
    push:
        branches:
          - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Setup Gleam
              uses: gleam-lang/setup-gleam@v1.0.2
            
            - uses: actions/setup-node@v4

            - name: Compile
              run: npm install; npm run start
